CompileFlags:
  Add:
    [
      -xc++,
      --target=x86_64-w64-windows-gnu,
      "-IC:\\MinGW\\lib\\gcc\\mingw32\\6.3.0\\include\\c++",
    ]
  Remove: -W* 
  Compiler: g++
InlayHints:
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
